### ISSUE TITLE
.rmd error - 'reshape' package

### ISSUE THREAD

**Issue by lauracorbin** [MRCIEU/MetaboQC#12]
When I ran the run_MetaboQC_pipeline.R script there was an error generated during the running of the .rmd report, as follows:

Quitting from lines 123-141 (QC_Report.Rmd) 
Error in loadNamespace(name) : there is no package called 'reshape'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart

I was able to fix this by manually installing the 'reshape' package prior to running the run_MetaboQC_pipeline.R script but presumably this package should be installed as a dependency as part of the main package install?

**Comment by hughesevoanth** [comment]
I have added the reshape package to the DESCRIPTION file. This should solve this problem.
