### ISSUE TITLE
error in QC_Report.Rmd 

### ISSUE THREAD

**Issue by lauracorbin** [MRCIEU/MetaboQC#13]
I am getting the following error back when the QC script reaches nearly the end (98%) of the .Rmd report:

Quitting from lines 751-763 (QC_Report.Rmd) 
Error in seq.default(100, half, 100) : wrong sign in 'by' argument
Calls: <Anonymous> ... run.pa.imbalanced.power.make.plot -> seq -> seq.default

**Comment by hughesevoanth** [comment]
This was a sample size issue. 
I wrote a new function to estimate an appropriate distribution of effect sizes for the given sample size (find.PA.effect.sizes.2.sim.R) to help over come this issue, and to have a nice distribution of effect sizes in the power plot from 0.2 power to a power of 1. 

Need to do the same for continuous traits now.
