### ISSUE TITLE
Check all log statements re. thresholds applied

### ISSUE THREAD

**Issue by lauracorbin** [MRCIEU/MetaboQC#2]
When including/excluding features/samples, in the code itself I think you generally use >=/<=, but then in the printed statements you just use >/<. This is a minor point but i think there needs to be consistency here as if people try to manually produce the same lists of inc/exclusions, if there are any values that are equal to the threshold it will cause slight discrepancies.

**Comment by hughesevoanth** [comment]
corrected in function perform.metabolite.qc.R
