### ISSUE TITLE
Possible inconsistency in perform.metabolite.qc.R

### ISSUE THREAD

**Issue by lauracorbin** [MRCIEU/MetaboQC#6]
It appears from the code, that if the user wants to they can opt not to make any sample exclusions based on TPA (by setting that to NA in the parameter file) ( "if( is.na(tpa_out_SD) == FALSE)" ) - although that's not clear in the readme or in the parameter file guidance (hashed out instructions in parameter file). 
This doesn't seem to be an option for the PCA based exclusions though. Question is, should it be? I guess you could just set the value really high to stop any exclusions being made anyway so maybe not that important. Could be one to put on the wish list to sort out?

**Comment by hughesevoanth** [comment]
Ok, I added NA as an option to PC exclusion and added info into the parameter file.
Respect for catching this !! You really combed through the scripts. THANK YOU !!!!!!
